- name: Ubuntu VM setup sudo for current user
  hosts: localhost
  vars:
    sudo_user: jst0417 
  tasks:
    - name: Sudo configuration for personal user
      ansible.builtin.copy:
        content: "{{ sudo_user }} ALL=(ALL) NOPASSWD: ALL\n"
        dest: "/etc/sudoers.d/{{ sudo_user }}"
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s
