---
- name: Install packages for apt and snap
  hosts: localhost
  vars_files:
    - apt-packages.yml
    - snap-packages.yml
    - flatpak-packages.yml
  tasks:
    - name: Install apt apps
      become: yes
      apt:
        name: "{{ apt_packages }}"
    - name: Install snap apps
      become: yes
      snap:
        name: "{{ snap_apps }}"
    - name: Add flatpak remote
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install flatpack packages
      flatpak:
        name: "{{ flatpak_apps }}"
        method: user
